
title: My Resume
url: 'http://daisyma.com'
baseurl: '/Macchiato123000.github.io' #change it according to your repository name



# Profile information
yourname: Qi Ma  ## put your name
title: 'Master Student @ UCSD &amp; Data Enthusiast'  ## your title
location: La Jolla , CA


## Social Profiles
facebook: https://www.facebook.com/qi.ma.33633  ## your facebook account url
email: maqi19950117@gmail.com  ## your email address
linkedin: https://linkedin.com/in/qi-ma/  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
